name: Deploy Hola Rentia

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Delegando a Cloudflare
        run: echo "El despliegue automático está delegado a Cloudflare Pages. Github Actions en verde."
